#################################################################################
# Licensed to the .NET Foundation under one or more agreements.                 #
# The .NET Foundation licenses this file to you under the MIT license.          #
# See the LICENSE file in the project root for more information.                #
#################################################################################
parameters:
  - name: debug
    type: boolean
    default: false

  - name: downloadedNugetPath # path to the downloaded nuget files
    type: string

  - name: nugetPackageVersion
    type: string
    default: $(NugetPackageVersion)

steps:
- powershell: |
    # Get a list of package sources available
    Get-PackageSource

    #Current location
    Get-Location

    # Register the local nuget folder to be used by nuget.config
    Register-PackageSource  -Name "Package Source" -Location ${{parameters.downloadedNugetPath }} -Force -ProviderName NuGet -Trusted

    # Get a list of package sources available after the change
    Get-PackageSource

    #Set the NuGet.config file in the project to use extracted package
    $rootFolder = Get-location
    [Xml] $nugetConfig = Get-Content -Path "NuGet.config"
    $Value = Resolve-Path ${{parameters.downloadedNugetPath }}
    $newAdd = $nugetConfig.CreateElement("add")
    $newAdd.SetAttribute("key","Package source")
    $newAdd.SetAttribute("value", "$Value/" )
    $nugetConfig.configuration.packageSources.AppendChild($newAdd)
    $nugetConfig.Save("$rootFolder/NuGet.config")
  displayName: 'Update NuGet config file to read from Nuget folder'

- ${{ if parameters.debug }}:
  - powershell: |
      # Display the content of the NuGet.config file
      Get-Content -Path "NuGet.config"
    displayName: 'Read NuGet.config [debug]'

- task: DotNetCoreCLI@2
  displayName: 'Restore NuGets'
  inputs:
    command: 'custom'
    custom: 'msbuild'
    arguments: 'build.proj -t:restore'
    feedsToUse: 'select'

- powershell: |
    $Doc = [xml](Get-Content "./Microsoft.Data.SqlClient.AlwaysEncrypted.AzureKeyVaultProvider.csproj")
    $parent_xpath = '/Project/ItemGroup/ProjectReference'
    $node = $Doc.SelectSingleNode($parent_xpath)
    $parentNode = $node.ParentNode
    while($node -ne $null) {
        $node.ParentNode.RemoveChild($node)
        $node = $Doc.SelectSingleNode($parent_xpath)
    }

    $parent_xpath = '/Project/ItemGroup/PackageReference[@Include="Microsoft.Data.SqlClient"]'
    $node = $Doc.SelectSingleNode($parent_xpath)
    
    if($node -ne $null){
        $node.Version="${{parameters.nugetPackageVersion }}"
    }
    else{
        $packagerefnode = $doc.createelement("packagereference")
        $value = $doc.selectsinglenode('/project/itemgroup/projectreference')
        $attrinclude = $doc.createattribute("include")
        $attrinclude.value = "microsoft.data.sqlclient"
        $attrversion = $doc.createattribute("version")
        $attrversion.value = "${{parameters.nugetPackageVersion }}"
        $packagerefnode.attributes.append($attrinclude)
        $packagerefnode.attributes.append($attrversion)
        $parentNode.AppendChild($packageRefNode)
    }

    $currentFolder = Get-Location
    $filePath = Join-Path $currentFolder "Microsoft.Data.SqlClient.AlwaysEncrypted.AzureKeyVaultProvider.csproj"
    $Doc.Save($filePath)
  workingDirectory: 'src/Microsoft.Data.SqlClient/add-ons/AzureKeyVaultProvider'
  displayName: 'Update AKV Project Ref to Package Ref (.NET Framework/Core)'
