version: '3.9'

services:
  microsoft.data.sqlclient.dockertests:
    image: ${DOCKER_REGISTRY-}microsoftdatasqlclientdockerlinuxtest
    build:
      context: ../
      dockerfile: src/Microsoft.Data.SqlClient/tests/Docker/DockerLinuxTest/Dockerfile
    depends_on:
      - microsoft.sqlserver

  microsoft.sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - SA_PASSWORD=P@ssw0rd!123
      - ACCEPT_EULA=Y
    ports:
      - "5434:1433"
